### ISSUE TITLE
Adding tenways mini-connector cable reference

### ISSUE THREAD

**Issue by vincent290587** [SenneRoot/VELOX#1]
Hi ! 
Cool project ;-)

Could you add the exact reference / link to the Tenways cable ?
I noticed it is smaller than the julet 5 pin more common ebike cables

**Comment by SenneRoot** [comment]
Hi! 

The cable from the display to the controller seems to be a 5 pin m6 connector with the following pinout:

![image](https://github.com/SenneRoot/VELOX/assets/19331519/73915576-7145-4a9a-98e5-51217816f1b6) ![image](https://github.com/SenneRoot/VELOX/assets/19331519/0c8fa952-3950-480a-8ff9-3c977938ac11)

| Pin |     | Function                             |
|-----|-----|--------------------------------------|
| 1   | VCC | Battery+ input                       |
| 2   | Kp  | Power control wire of the controller |
| 3   | GND | GND                                  |
| 4   | RX  | Data receive of the display          |
| 5   | TX  | Data transmit of the display         |


I've ordered the cables from aliexpress and it seems the colors of these wires are all over the place. So its a good practice to measure the pins before connecting anything, I've actually blown a display.

**Comment by FortunaD** [comment]
Thanks for the detailed pinout.
I‘m not sure if I connected the pinouts correctly. 
Are this RX and TX pins designation belongs to the bike display or to the Arduino ? 
I connected pin 5 TX to RX of Arduino. Is it correct?
